from __future__ import annotations

from pathlib import Path
import re
import shlex
import shutil

from .parallel import write_edmft_mpi_prefix, write_wien_machines
from .utils import (
    WorkflowError,
    copy_case_files,
    require_file,
    run_stage,
    safe_prepare_dir,
)


def init_layout(cfg) -> None:
    """Create the fixed project layout without running either initializer."""
    cfg.root_dir.mkdir(parents=True, exist_ok=True)
    (cfg.root_dir / "inputs").mkdir(parents=True, exist_ok=True)
    cfg.dft_dir.mkdir(parents=True, exist_ok=True)
    cfg.dmft_dir.mkdir(parents=True, exist_ok=True)
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)
    print(f"project root : {cfg.root_dir}")
    print(f"inputs dir   : {cfg.root_dir / 'inputs'}")
    print(f"DFT dir      : {cfg.dft_dir}")
    print(f"DMFT dir     : {cfg.dmft_dir}")
    print(f"DFT SCRATCH  : {cfg.scratch_dir}")
    print("Manual checkpoint 1: cd dft && export SCRATCH=$PWD/tmp && init_lapw")
    print("After DFT convergence, manual checkpoint 2 is init_dmft.py in the SAME dft/ directory.")


def _edmft_command(cfg, name: str) -> str:
    key = name.replace(".py", "").replace("-", "_")
    configured = cfg.get(f"commands.{key}")
    if configured:
        return str(configured)
    root = cfg.get("environment.edmft_root")
    if not root:
        raise WorkflowError(f"environment.edmft_root is required to locate {name}")
    return str(Path(str(root)) / name)


def run_dft(cfg) -> Path:
    """Foreground/debug runner retained for compatibility; production uses static PBS."""
    case = cfg.case
    require_file(cfg.dft_dir / f"{case}.struct")
    require_file(cfg.dft_dir / f"{case}.in0")
    require_file(cfg.dft_dir / f"{case}.in1")
    klist = require_file(cfg.dft_dir / f"{case}.klist")
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)
    write_wien_machines(cfg, cfg.dft_dir, klist, "dft")
    cmd = str(cfg.get("dft.run_command", "run_lapw -p -ec 0.0001 -cc 0.0001"))
    if " -p" not in f" {cmd} ":
        cmd += " -p"
    run_stage(cfg, cmd, cwd=cfg.dft_dir, scratch=cfg.scratch_dir,
              log=cfg.dft_dir / "edmft_workflow_dft.log")
    require_file(cfg.dft_dir / f"{case}.scf")
    return cfg.dft_dir


def _python_literal(value) -> str:
    if isinstance(value, dict):
        raise WorkflowError("Nested tables are not supported inside dmft_params/impurityN sections")
    return repr(value)


def render_params_dat(cfg) -> str:
    """Fallback renderer when inputs/params.dat is not supplied explicitly."""
    global_params = cfg.section("dmft_params")
    if not global_params:
        raise WorkflowError(
            "No inputs/params.dat and no [dmft_params] in config.toml. "
            "Refusing to invent physical DMFT parameters."
        )

    impurities: list[tuple[int, dict]] = []
    for name, value in cfg.data.items():
        m = re.fullmatch(r"impurity(\d+)", str(name))
        if m and isinstance(value, dict):
            impurities.append((int(m.group(1)), dict(value)))
    impurities.sort(key=lambda x: x[0])
    if not impurities or impurities[0][0] != 0 or not impurities[0][1]:
        raise WorkflowError(
            "No inputs/params.dat and missing non-empty [impurity0] in config.toml."
        )

    lines = [
        "# Generated by edmft_workflow from config.toml.",
        "# Prefer PROJECT/inputs/params.dat when you want a fully native eDMFT input.",
        "",
    ]
    for key, value in global_params.items():
        lines.append(f"{key} = {_python_literal(value)}")
    for idx, params in impurities:
        lines += ["", f"iparams{idx} = {{"]
        for key, value in params.items():
            lines.append(f"    {key!r}: [{_python_literal(value)}, ''],")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _nonempty(path: Path) -> bool:
    return path.is_file() and path.stat().st_size > 0


def _require_any_case_file(directory: Path, case: str, suffixes: tuple[str, ...], label: str) -> Path:
    for suffix in suffixes:
        path = directory / f"{case}.{suffix}"
        if _nonempty(path):
            return path
    names = ", ".join(f"{case}.{s}" for s in suffixes)
    raise WorkflowError(f"Missing {label} in {directory}. Need one of: {names}")


def _validate_potential_set(directory: Path, case: str) -> str:
    base = ("vsp", "vns")
    spin = ("vspup", "vspdn", "vnsup", "vnsdn")
    if all(_nonempty(directory / f"{case}.{s}") for s in base):
        return "nonmagnetic"
    if all(_nonempty(directory / f"{case}.{s}") for s in spin):
        return "spin-polarized"
    raise WorkflowError(
        f"Incomplete WIEN2k potential state in {directory}. Need either "
        f"{case}.vsp + {case}.vns, or the complete "
        f"{case}.vspup/{case}.vspdn/{case}.vnsup/{case}.vnsdn set."
    )


def _validate_dft_ready(cfg) -> None:
    case = cfg.case
    required = ("struct", "in0", "inm", "klist", "clmsum", "scf", "indmf", "indmfl", "indmfi")
    for suffix in required:
        require_file(cfg.dft_dir / f"{case}.{suffix}")
    _require_any_case_file(cfg.dft_dir, case, ("in1", "in1c"), "WIEN2k LAPW1 input")
    _require_any_case_file(cfg.dft_dir, case, ("in2", "in2c"), "WIEN2k LAPW2 input")
    _validate_potential_set(cfg.dft_dir, case)


def _prepare_clean_dmft_dir(cfg, force: bool) -> None:
    dmft = cfg.dmft_dir
    if dmft.exists():
        tmp = dmft / "tmp"
        if tmp.is_dir() and not any(tmp.iterdir()):
            tmp.rmdir()
        if any(dmft.iterdir()):
            safe_prepare_dir(dmft, force=force)
        else:
            dmft.mkdir(parents=True, exist_ok=True)
    else:
        dmft.mkdir(parents=True, exist_ok=True)


def _copy_dft_state_extras(cfg) -> None:
    case = cfg.case
    source = cfg.dft_dir
    target = cfg.dmft_dir
    copy_case_files(source, target, case, ["indmf"], required=True)
    copy_case_files(
        source, target, case,
        ["vsp", "vns", "vspup", "vspdn", "vnsup", "vnsdn", "vrespsum"],
        required=False,
    )


def _prepare_params_dat(cfg) -> tuple[Path, str]:
    target = cfg.dmft_dir / "params.dat"
    supplied = cfg.root_dir / "inputs" / "params.dat"
    if supplied.exists():
        require_file(supplied)
        shutil.copy2(supplied, target)
        return require_file(target), str(supplied)
    target.write_text(render_params_dat(cfg), encoding="utf-8")
    return require_file(target), "generated from config.toml"


def _prepare_initial_sigma(cfg) -> Path:
    mode = str(cfg.get("dmft_prepare.initial_sigma", "szero")).lower()
    sig = cfg.dmft_dir / "sig.inp"
    if mode == "keep":
        return require_file(sig)
    if mode != "szero":
        raise WorkflowError("dmft_prepare.initial_sigma must be 'szero' or 'keep'")

    szero = _edmft_command(cfg, "szero.py")
    extra = cfg.get("dmft_prepare.szero_args", [])
    if isinstance(extra, str):
        extra = shlex.split(extra)
    run_stage(
        cfg, [szero, *[str(x) for x in extra]], cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir, log=cfg.dmft_dir / "szero.log",
    )
    return require_file(sig)


def _validate_dmft_snapshot(cfg) -> None:
    case = cfg.case
    for suffix in ("struct", "in0", "inm", "klist", "clmsum", "indmf", "indmfl", "indmfi"):
        require_file(cfg.dmft_dir / f"{case}.{suffix}")
    _require_any_case_file(cfg.dmft_dir, case, ("in1", "in1c"), "WIEN2k LAPW1 input")
    _require_any_case_file(cfg.dmft_dir, case, ("in2", "in2c"), "WIEN2k LAPW2 input")
    _validate_potential_set(cfg.dmft_dir, case)
    require_file(cfg.dmft_dir / "params.dat")
    require_file(cfg.dmft_dir / "sig.inp")
    if not cfg.dmft_scratch_dir.is_dir():
        raise WorkflowError(f"DMFT scratch directory was not created: {cfg.dmft_scratch_dir}")


def prepare_dmft(cfg, force: bool = False) -> Path:
    """Create an isolated DMFT snapshot after DFT + manual init_dmft.py in dft/."""
    _validate_dft_ready(cfg)
    # Validate the params source before backing up any existing dmft/ directory.
    supplied = cfg.root_dir / "inputs" / "params.dat"
    if not supplied.exists():
        render_params_dat(cfg)
    else:
        require_file(supplied)

    _prepare_clean_dmft_dir(cfg, force=force)
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)

    dmft_copy = _edmft_command(cfg, "dmft_copy.py")
    run_stage(
        cfg, [dmft_copy, str(cfg.dft_dir)], cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir, log=cfg.dmft_dir / "dmft_copy_from_dft.log",
    )
    _copy_dft_state_extras(cfg)

    params, params_source = _prepare_params_dat(cfg)
    sig = _prepare_initial_sigma(cfg)
    _validate_dmft_snapshot(cfg)

    print(f"DMFT working snapshot prepared: {cfg.dmft_dir}")
    print(f"params.dat                  : {params}")
    print(f"params source               : {params_source}")
    print(f"Initial self-energy         : {sig}")
    print("DMFT snapshot READY")
    print("Next: inspect params.dat and sig.inp, generate static PBS with `pbs dmft`, then qsub it manually.")
    return cfg.dmft_dir


def run_dmft(cfg) -> Path:
    """Foreground/debug runner retained for compatibility; production uses static PBS."""
    case = cfg.case
    _validate_dmft_snapshot(cfg)
    klist = require_file(cfg.dmft_dir / f"{case}.klist")
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)
    write_edmft_mpi_prefix(cfg, cfg.dmft_dir, "dmft")
    if bool(cfg.get("parallel.dmft_wien_machines", False)):
        write_wien_machines(cfg, cfg.dmft_dir, klist, "dmft")
    py = str(cfg.get("environment.python", "python"))
    root = cfg.get("environment.edmft_root")
    if not root:
        raise WorkflowError("environment.edmft_root is required to locate run_dmft.py")
    cmd = f"{shlex.quote(py)} {shlex.quote(str(Path(str(root)) / 'run_dmft.py'))}"
    run_stage(cfg, cmd, cwd=cfg.dmft_dir, scratch=cfg.dmft_scratch_dir,
              log=cfg.dmft_dir / "run_dmft.log")
    require_file(cfg.dmft_dir / "info.iterate")
    return cfg.dmft_dir
