from __future__ import annotations

from pathlib import Path
import re
import shlex

from .parallel import write_edmft_mpi_prefix, write_wien_machines
from .utils import (
    WorkflowError,
    copy_case_files,
    require_file,
    run_stage,
    safe_prepare_dir,
)


def init_layout(cfg) -> None:
    """Create the fixed project layout without running either initializer."""
    cfg.dft_dir.mkdir(parents=True, exist_ok=True)
    cfg.dmft_dir.mkdir(parents=True, exist_ok=True)
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)
    print(f"project root : {cfg.root_dir}")
    print(f"DFT dir      : {cfg.dft_dir}")
    print(f"DMFT dir     : {cfg.dmft_dir}")
    print(f"DFT SCRATCH  : {cfg.scratch_dir}")
    print("Manual checkpoint 1: cd dft && export SCRATCH=$PWD/tmp && init_lapw")
    print("After DFT convergence, manual checkpoint 2 is init_dmft.py in the SAME dft/ directory.")


def run_dft(cfg) -> Path:
    """Run the ordinary WIEN2k DFT calculation after manual `init_lapw`."""
    case = cfg.case
    require_file(cfg.dft_dir / f"{case}.struct")
    require_file(cfg.dft_dir / f"{case}.in0")
    require_file(cfg.dft_dir / f"{case}.in1")
    klist = require_file(cfg.dft_dir / f"{case}.klist")
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)

    # WIEN2k k-point parallelism is controlled by .machines + run_lapw -p.
    write_wien_machines(cfg, cfg.dft_dir, klist, "dft")

    cmd = str(cfg.get("dft.run_command", "run_lapw -p -ec 0.0001 -cc 0.0001"))
    if " -p" not in f" {cmd} ":
        cmd += " -p"
    run_stage(
        cfg,
        cmd,
        cwd=cfg.dft_dir,
        scratch=cfg.scratch_dir,
        log=cfg.dft_dir / "edmft_workflow_dft.log",
    )
    require_file(cfg.dft_dir / f"{case}.scf")
    print(f"DFT run complete: {cfg.dft_dir}")
    print("Next MANUAL checkpoint: run init_dmft.py in this converged dft/ directory.")
    print("After inspecting case.indmf/indmfl/indmfi, run prepare-dmft.")
    return cfg.dft_dir


def _python_literal(value) -> str:
    """Render TOML scalar/list values as safe Python literals for params.dat."""
    if isinstance(value, dict):
        raise WorkflowError("Nested tables are not supported inside dmft_params/impurityN sections")
    return repr(value)


def render_params_dat(cfg) -> str:
    """Render Haule-style params.dat from config sections.

    Top-level `[dmft_params]` keys become ordinary Python assignments, while
    `[impurity0]`, `[impurity1]`, ... become `iparams0`, `iparams1`, ...
    dictionaries. eDMFT impurity parameters use the conventional
    `[value, comment]` representation; generated comments are intentionally
    empty because the authoritative values live in config.toml.
    """
    global_params = cfg.section("dmft_params")
    if not global_params:
        raise WorkflowError(
            "Missing [dmft_params] in config.toml. Refusing to invent physical DMFT parameters."
        )

    impurities: list[tuple[int, dict]] = []
    for name, value in cfg.data.items():
        m = re.fullmatch(r"impurity(\d+)", str(name))
        if m and isinstance(value, dict):
            impurities.append((int(m.group(1)), dict(value)))
    impurities.sort(key=lambda x: x[0])
    if not impurities or impurities[0][0] != 0 or not impurities[0][1]:
        raise WorkflowError(
            "Missing non-empty [impurity0] in config.toml. At least one impurity parameter block is required."
        )

    lines = [
        "# Generated by edmft_workflow from config.toml.",
        "# Edit config.toml, not this generated file, for reproducible reruns.",
        "",
    ]
    for key, value in global_params.items():
        lines.append(f"{key} = {_python_literal(value)}")

    for idx, params in impurities:
        lines += ["", f"iparams{idx} = {{"]
        for key, value in params.items():
            lines.append(f"    {key!r}: [{_python_literal(value)}, ''],")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _nonempty(path: Path) -> bool:
    return path.is_file() and path.stat().st_size > 0


def _require_any_case_file(directory: Path, case: str, suffixes: tuple[str, ...], label: str) -> Path:
    for suffix in suffixes:
        path = directory / f"{case}.{suffix}"
        if _nonempty(path):
            return path
    names = ", ".join(f"{case}.{s}" for s in suffixes)
    raise WorkflowError(f"Missing {label} in {directory}. Need one of: {names}")


def _validate_potential_set(directory: Path, case: str) -> str:
    """Require a complete nonmagnetic or spin-polarized WIEN2k potential set."""
    base = ("vsp", "vns")
    spin = ("vspup", "vspdn", "vnsup", "vnsdn")
    if all(_nonempty(directory / f"{case}.{s}") for s in base):
        return "nonmagnetic"
    if all(_nonempty(directory / f"{case}.{s}") for s in spin):
        return "spin-polarized"
    raise WorkflowError(
        f"Incomplete WIEN2k potential state in {directory}. Need either "
        f"{case}.vsp + {case}.vns, or the complete "
        f"{case}.vspup/{case}.vspdn/{case}.vnsup/{case}.vnsdn set."
    )


def _validate_dft_ready(cfg) -> None:
    """Verify converged DFT + manual init_dmft.py before touching dmft/."""
    case = cfg.case
    required = (
        "struct",
        "in0",
        "inm",
        "klist",
        "clmsum",
        "scf",
        "indmf",
        "indmfl",
        "indmfi",
    )
    for suffix in required:
        require_file(cfg.dft_dir / f"{case}.{suffix}")

    _require_any_case_file(cfg.dft_dir, case, ("in1", "in1c"), "WIEN2k LAPW1 input")
    _require_any_case_file(cfg.dft_dir, case, ("in2", "in2c"), "WIEN2k LAPW2 input")
    _validate_potential_set(cfg.dft_dir, case)


def _prepare_clean_dmft_dir(cfg, force: bool) -> None:
    """Prepare dmft/ as an isolated snapshot directory.

    Older `init-layout` versions created an empty dmft/tmp. Ignore/remove that
    empty housekeeping directory so a first prepare-dmft does not falsely look
    like an existing calculation. Any real payload requires --force, which
    backs up the whole previous dmft/ directory before recreating it.
    """
    dmft = cfg.dmft_dir
    if dmft.exists():
        tmp = dmft / "tmp"
        if tmp.is_dir() and not any(tmp.iterdir()):
            tmp.rmdir()
        if any(dmft.iterdir()):
            safe_prepare_dir(dmft, force=force)
        else:
            dmft.mkdir(parents=True, exist_ok=True)
    else:
        dmft.mkdir(parents=True, exist_ok=True)


def _copy_dft_state_extras(cfg) -> None:
    """Copy converged WIEN2k state omitted by upstream dmft_copy.py."""
    case = cfg.case
    source = cfg.dft_dir
    target = cfg.dmft_dir

    # Preserve the original correlated-space definition. Upstream dmft_copy.py
    # copies indmfl/indmfi but not the human-readable case.indmf.
    copy_case_files(source, target, case, ["indmf"], required=True)

    # Current upstream dmft_copy.py does not copy converged potential files.
    # They are mutable during charge-self-consistent DMFT, so COPY them rather
    # than symlinking them back to the DFT baseline.
    suffixes = ["vsp", "vns", "vspup", "vspdn", "vnsup", "vnsdn", "vrespsum"]
    copy_case_files(source, target, case, suffixes, required=False)


def _prepare_initial_sigma(cfg) -> Path:
    mode = str(cfg.get("dmft_prepare.initial_sigma", "szero")).lower()
    sig = cfg.dmft_dir / "sig.inp"

    if mode == "keep":
        return require_file(sig)
    if mode != "szero":
        raise WorkflowError("dmft_prepare.initial_sigma must be 'szero' or 'keep'")

    szero = str(cfg.get("commands.szero", "szero.py"))
    extra = cfg.get("dmft_prepare.szero_args", [])
    if isinstance(extra, str):
        extra = shlex.split(extra)
    run_stage(
        cfg,
        [szero, *[str(x) for x in extra]],
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "szero.log",
    )
    return require_file(sig)


def _validate_dmft_snapshot(cfg) -> None:
    """Final READY gate before prepare-dmft returns success."""
    case = cfg.case
    required_case = (
        "struct",
        "in0",
        "inm",
        "klist",
        "clmsum",
        "indmf",
        "indmfl",
        "indmfi",
    )
    for suffix in required_case:
        require_file(cfg.dmft_dir / f"{case}.{suffix}")

    _require_any_case_file(cfg.dmft_dir, case, ("in1", "in1c"), "WIEN2k LAPW1 input")
    _require_any_case_file(cfg.dmft_dir, case, ("in2", "in2c"), "WIEN2k LAPW2 input")
    _validate_potential_set(cfg.dmft_dir, case)

    require_file(cfg.dmft_dir / "params.dat")
    require_file(cfg.dmft_dir / "sig.inp")
    if not cfg.dmft_scratch_dir.is_dir():
        raise WorkflowError(f"DMFT scratch directory was not created: {cfg.dmft_scratch_dir}")


def prepare_dmft(cfg, force: bool = False) -> Path:
    """Create an isolated DMFT working snapshot after manual init_dmft.py in dft/.

    Required order:
      1. converged WIEN2k DFT in dft/
      2. user runs init_dmft.py manually in that SAME dft/ directory
      3. prepare-dmft copies the initialized state into a separate dmft/
      4. workflow generates params.dat and initial sig.inp in dmft/
      5. final READY validation must pass before the command returns success

    `dmft_copy.py SOURCE` copies FROM SOURCE INTO THE CURRENT DIRECTORY, hence
    it is executed with cwd=dmft/ and dft/ as its positional source argument.
    The dmft/ snapshot contains real copies of mutable WIEN2k state; it never
    symlinks numerical input/output files back to the DFT baseline.
    """
    case = cfg.case

    # Validate DFT + init_dmft.py completely BEFORE touching an older dmft/ run.
    _validate_dft_ready(cfg)
    params_text = render_params_dat(cfg)

    # Protect an existing DMFT run. --force creates a timestamped backup first.
    _prepare_clean_dmft_dir(cfg, force=force)
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)

    # Haule convention: dmft_copy.py SOURCE copies into the CURRENT directory.
    dmft_copy = str(cfg.get("commands.dmft_copy", "dmft_copy.py"))
    run_stage(
        cfg,
        [dmft_copy, str(cfg.dft_dir)],
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "dmft_copy_from_dft.log",
    )

    # Supplement files intentionally omitted by upstream dmft_copy.py.
    _copy_dft_state_extras(cfg)

    # Generate run-specific DMFT inputs only after the DFT snapshot exists.
    params = cfg.dmft_dir / "params.dat"
    params.write_text(params_text, encoding="utf-8")
    require_file(params)
    sig = _prepare_initial_sigma(cfg)

    # Do not report success merely because copy/szero exited zero.
    _validate_dmft_snapshot(cfg)

    print(f"DMFT working snapshot prepared: {cfg.dmft_dir}")
    print(f"Generated params.dat         : {params}")
    print(f"Initial self-energy          : {sig}")
    print("DMFT snapshot READY")
    print("Next: inspect params.dat and sig.inp, then submit dmft.")
    return cfg.dmft_dir


def run_dmft(cfg) -> Path:
    """Run Haule's charge-self-consistent DFT+DMFT in the isolated dmft/ snapshot."""
    case = cfg.case
    _validate_dmft_snapshot(cfg)
    klist = require_file(cfg.dmft_dir / f"{case}.klist")
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)

    write_edmft_mpi_prefix(cfg, cfg.dmft_dir, "dmft")
    if bool(cfg.get("parallel.dmft_wien_machines", False)):
        write_wien_machines(cfg, cfg.dmft_dir, klist, "dmft")

    cmd = cfg.get("dmft.run_command")
    if not cmd:
        py = str(cfg.get("environment.python", "python"))
        root = cfg.get("environment.edmft_root")
        if not root:
            raise WorkflowError("environment.edmft_root is required to locate run_dmft.py")
        cmd = f"{shlex.quote(py)} {shlex.quote(str(Path(str(root)) / 'run_dmft.py'))}"

    run_stage(
        cfg,
        str(cmd),
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "run_dmft.log",
    )
    require_file(cfg.dmft_dir / "info.iterate")
    print(f"DMFT run complete: {cfg.dmft_dir}")
    return cfg.dmft_dir
