from __future__ import annotations

from pathlib import Path
import os
import re
import shlex
import shutil

from .parallel import write_edmft_mpi_prefix, write_wien_machines
from .utils import (
    WorkflowError,
    copy_case_files,
    require_file,
    run_stage,
    safe_prepare_dir,
)


def init_layout(cfg) -> None:
    """Create the fixed project layout without running either initializer."""
    cfg.dft_dir.mkdir(parents=True, exist_ok=True)
    cfg.dmft_dir.mkdir(parents=True, exist_ok=True)
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)
    print(f"project root : {cfg.root_dir}")
    print(f"DFT dir      : {cfg.dft_dir}")
    print(f"DMFT dir     : {cfg.dmft_dir}")
    print(f"DFT SCRATCH  : {cfg.scratch_dir}")
    print("Manual checkpoint 1: cd dft && export SCRATCH=$PWD/tmp && init_lapw")
    print("After DFT convergence, manual checkpoint 2 is init_dmft.py in the SAME dft/ directory.")


def run_dft(cfg) -> Path:
    """Run the ordinary WIEN2k DFT calculation after manual `init_lapw`."""
    case = cfg.case
    require_file(cfg.dft_dir / f"{case}.struct")
    require_file(cfg.dft_dir / f"{case}.in0")
    require_file(cfg.dft_dir / f"{case}.in1")
    klist = require_file(cfg.dft_dir / f"{case}.klist")
    cfg.scratch_dir.mkdir(parents=True, exist_ok=True)

    # WIEN2k k-point parallelism is controlled by .machines + run_lapw -p.
    write_wien_machines(cfg, cfg.dft_dir, klist, "dft")

    cmd = str(cfg.get("dft.run_command", "run_lapw -p -ec 0.0001 -cc 0.0001"))
    if " -p" not in f" {cmd} ":
        cmd += " -p"
    run_stage(
        cfg,
        cmd,
        cwd=cfg.dft_dir,
        scratch=cfg.scratch_dir,
        log=cfg.dft_dir / "edmft_workflow_dft.log",
    )
    require_file(cfg.dft_dir / f"{case}.scf")
    print(f"DFT run complete: {cfg.dft_dir}")
    print("Next MANUAL checkpoint: run init_dmft.py in this converged dft/ directory.")
    print("After inspecting case.indmf/indmfl/indmfi, run prepare-dmft.")
    return cfg.dft_dir


def _python_literal(value) -> str:
    """Render TOML scalar/list values as safe Python literals for params.dat."""
    if isinstance(value, dict):
        raise WorkflowError("Nested tables are not supported inside dmft_params/impurityN sections")
    return repr(value)


def render_params_dat(cfg) -> str:
    """Render Haule-style params.dat from config sections.

    Top-level `[dmft_params]` keys become ordinary Python assignments, while
    `[impurity0]`, `[impurity1]`, ... become `iparams0`, `iparams1`, ...
    dictionaries.  eDMFT impurity parameters use the conventional
    `[value, comment]` representation; generated comments are intentionally
    empty because the authoritative values live in config.toml.
    """
    global_params = cfg.section("dmft_params")
    if not global_params:
        raise WorkflowError(
            "Missing [dmft_params] in config.toml. Refusing to invent physical DMFT parameters."
        )

    impurities: list[tuple[int, dict]] = []
    for name, value in cfg.data.items():
        m = re.fullmatch(r"impurity(\d+)", str(name))
        if m and isinstance(value, dict):
            impurities.append((int(m.group(1)), dict(value)))
    impurities.sort(key=lambda x: x[0])
    if not impurities or impurities[0][0] != 0 or not impurities[0][1]:
        raise WorkflowError(
            "Missing non-empty [impurity0] in config.toml. At least one impurity parameter block is required."
        )

    lines = [
        "# Generated by edmft_workflow from config.toml.",
        "# Edit config.toml, not this generated file, for reproducible reruns.",
        "",
    ]
    for key, value in global_params.items():
        lines.append(f"{key} = {_python_literal(value)}")

    for idx, params in impurities:
        lines += ["", f"iparams{idx} = {{"]
        for key, value in params.items():
            lines.append(f"    {key!r}: [{_python_literal(value)}, ''],")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def _prepare_clean_dmft_dir(cfg, force: bool) -> None:
    """Prepare dmft/ as an isolated snapshot directory.

    Older `init-layout` versions created an empty dmft/tmp.  Ignore/remove that
    empty housekeeping directory so a first prepare-dmft does not falsely look
    like an existing calculation.  Any real payload requires --force, which
    backs up the whole previous dmft/ directory before recreating it.
    """
    dmft = cfg.dmft_dir
    if dmft.exists():
        tmp = dmft / "tmp"
        if tmp.is_dir() and not any(tmp.iterdir()):
            tmp.rmdir()
        if any(dmft.iterdir()):
            safe_prepare_dir(dmft, force=force)
        else:
            dmft.mkdir(parents=True, exist_ok=True)
    else:
        dmft.mkdir(parents=True, exist_ok=True)


def _copy_dft_state_extras(cfg) -> None:
    """Copy converged WIEN2k state omitted by upstream dmft_copy.py."""
    case = cfg.case
    source = cfg.dft_dir
    target = cfg.dmft_dir

    # Keep the human-readable DMFT model definition for provenance.  Upstream
    # dmft_copy.py copies indmfl/indmfi but not the original case.indmf.
    copy_case_files(source, target, case, ["indmf"], required=True)

    # Current upstream dmft_copy.py does not copy converged potential files.
    # They are mutable during charge-self-consistent DMFT, so COPY them rather
    # than symlinking them back to the DFT baseline.
    suffixes = ["vsp", "vns", "vspup", "vspdn", "vnsup", "vnsdn", "vrespsum"]
    copy_case_files(source, target, case, suffixes, required=False)

    base_ok = all((source / f"{case}.{s}").is_file() and (source / f"{case}.{s}").stat().st_size > 0
                  for s in ("vsp", "vns"))
    spin_ok = all((source / f"{case}.{s}").is_file() and (source / f"{case}.{s}").stat().st_size > 0
                  for s in ("vspup", "vspdn", "vnsup", "vnsdn"))
    if not (base_ok or spin_ok):
        raise WorkflowError(
            "Converged DFT potential files are incomplete. Need case.vsp+case.vns "
            "or a complete spin-polarized vspup/vspdn/vnsup/vnsdn set."
        )


def _write_dft_source_link(cfg) -> Path:
    """Create a provenance-only symlink; numerical files never run through it."""
    link = cfg.dmft_dir / "DFT_SOURCE"
    if link.exists() or link.is_symlink():
        link.unlink()
    target = os.path.relpath(cfg.dft_dir, cfg.dmft_dir)
    link.symlink_to(target, target_is_directory=True)
    return link


def _prepare_initial_sigma(cfg) -> Path:
    mode = str(cfg.get("dmft_prepare.initial_sigma", "szero")).lower()
    sig = cfg.dmft_dir / "sig.inp"

    if mode == "keep":
        return require_file(sig)
    if mode != "szero":
        raise WorkflowError("dmft_prepare.initial_sigma must be 'szero' or 'keep'")

    szero = str(cfg.get("commands.szero", "szero.py"))
    extra = cfg.get("dmft_prepare.szero_args", [])
    if isinstance(extra, str):
        extra = shlex.split(extra)
    run_stage(
        cfg,
        [szero, *[str(x) for x in extra]],
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "szero.log",
    )
    return require_file(sig)


def prepare_dmft(cfg, force: bool = False) -> Path:
    """Create an isolated DMFT working snapshot after manual init_dmft.py in dft/.

    Required order:
      1. converged WIEN2k DFT in dft/
      2. user runs init_dmft.py manually in that SAME dft/ directory
      3. prepare-dmft copies the initialized state into a separate dmft/
      4. workflow generates params.dat and initial sig.inp in dmft/

    `dmft_copy.py SOURCE` copies FROM SOURCE INTO THE CURRENT DIRECTORY, hence
    it is executed with cwd=dmft/ and dft/ as its positional source argument.
    """
    case = cfg.case

    # Validate everything that should exist BEFORE touching an older dmft/ run.
    for name in [
        f"{case}.struct",
        f"{case}.scf",
        f"{case}.indmf",
        f"{case}.indmfl",
        f"{case}.indmfi",
    ]:
        require_file(cfg.dft_dir / name)
    params_text = render_params_dat(cfg)

    _prepare_clean_dmft_dir(cfg, force=force)
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)

    dmft_copy = str(cfg.get("commands.dmft_copy", "dmft_copy.py"))
    run_stage(
        cfg,
        [dmft_copy, str(cfg.dft_dir)],
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "dmft_copy_from_dft.log",
    )

    require_file(cfg.dmft_dir / f"{case}.struct")
    require_file(cfg.dmft_dir / f"{case}.indmfl")
    require_file(cfg.dmft_dir / f"{case}.indmfi")
    _copy_dft_state_extras(cfg)
    source_link = _write_dft_source_link(cfg)

    params = cfg.dmft_dir / "params.dat"
    params.write_text(params_text, encoding="utf-8")
    require_file(params)
    sig = _prepare_initial_sigma(cfg)

    print(f"DMFT working snapshot prepared: {cfg.dmft_dir}")
    print(f"DFT provenance link          : {source_link} -> {os.readlink(source_link)}")
    print(f"Generated params.dat         : {params}")
    print(f"Initial self-energy          : {sig}")
    print("No further initialization is required. Next: inspect the snapshot, then submit dmft.")
    return cfg.dmft_dir


def run_dmft(cfg) -> Path:
    """Run Haule's charge-self-consistent DFT+DMFT in the isolated dmft/ snapshot."""
    case = cfg.case
    require_file(cfg.dmft_dir / f"{case}.struct")
    require_file(cfg.dmft_dir / f"{case}.indmfl")
    require_file(cfg.dmft_dir / f"{case}.indmfi")
    require_file(cfg.dmft_dir / "params.dat")
    require_file(cfg.dmft_dir / "sig.inp")
    klist = require_file(cfg.dmft_dir / f"{case}.klist")
    cfg.dmft_scratch_dir.mkdir(parents=True, exist_ok=True)

    write_edmft_mpi_prefix(cfg, cfg.dmft_dir, "dmft")
    if bool(cfg.get("parallel.dmft_wien_machines", False)):
        write_wien_machines(cfg, cfg.dmft_dir, klist, "dmft")

    cmd = cfg.get("dmft.run_command")
    if not cmd:
        py = str(cfg.get("environment.python", "python"))
        root = cfg.get("environment.edmft_root")
        if not root:
            raise WorkflowError("environment.edmft_root is required to locate run_dmft.py")
        cmd = f"{shlex.quote(py)} {shlex.quote(str(Path(str(root)) / 'run_dmft.py'))}"

    run_stage(
        cfg,
        str(cmd),
        cwd=cfg.dmft_dir,
        scratch=cfg.dmft_scratch_dir,
        log=cfg.dmft_dir / "run_dmft.log",
    )
    require_file(cfg.dmft_dir / "info.iterate")
    print(f"DMFT run complete: {cfg.dmft_dir}")
    return cfg.dmft_dir
